title   CachyOS Mac Pro 6,1 %ARCH% UEFI
sort-key A
linux   /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux-macpro61
initrd  /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux-macpro61.img
options archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID% cow_spacesize=10G copytoram=auto module_blacklist=pcspkr amdgpu.si_support=1 amdgpu.dc=0 acpi_mask_gpe=0x16 nvme_load=yes
