title   CachyOS LTS %ARCH% UEFI Fallback
sort-key B
linux   /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux-cachyos-lts
initrd  /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux-cachyos-lts.img
options archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID% cow_spacesize=10G copytoram=auto module_blacklist=pcspkr amdgpu.si_support=1 amdgpu.dc=0 acpi_mask_gpe=0x16 nvme_load=yes
